spring.application.name=online_shop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.validate
spring.flyway.enabled=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

onlineshop.app.secret=${APP_JWT_SECRET}
onlineshop.app.admin.username=${APP_ADMIN_USERNAME}
onlineshop.app.admin.password=${APP_ADMIN_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
app.cors.allowed-origins=${APP_CORS_ORIGINS}


spring.jpa.hibernate.ddl-auto=update
